String[] backup;
File[] test =new File(sketchPath("main_combined_games.pde")).listFiles();
void backup() {
  printArray(test);
  backup=loadStrings("backup.pde");
  saveStrings(saveLocation+"backup/backup.pde", backup);
  backup=loadStrings("main_combined_games.pde");
  saveStrings(saveLocation+"backup/main_combined_games.pde", backup);
  backup=loadStrings("c4_connect_four.pde");
  saveStrings(saveLocation+"backup/c4_connect_four.pde", backup);
  backup=loadStrings("FB_flappy_bird.pde");
  saveStrings(saveLocation+"backup/FB_flappy_bird.pde", backup);
  backup=loadStrings("life_game_of_life.pde");
  saveStrings(saveLocation+"backup/life_game_of_life.pde", backup);
  backup=loadStrings("m_game_end.pde");
  saveStrings(saveLocation+"backup/m_game_end.pde", backup);
  backup=loadStrings("m_mancala.pde");
  saveStrings(saveLocation+"backup/m_mancala.pde", backup);
  backup=loadStrings("m_movingdown.pde");
  saveStrings(saveLocation+"backup/m_movingdown.pde", backup);
  backup=loadStrings("m_movingup.pde");
  saveStrings(saveLocation+"backup/m_movingup.pde", backup);
  backup=loadStrings("pente.pde");
  saveStrings(saveLocation+"backup/pente.pde", backup);
  backup=loadStrings("snake.pde");
  saveStrings(saveLocation+"backup/snake.pde", backup);
  backup=loadStrings("snakeMirrorMode.pde");
  saveStrings(saveLocation+"backup/snakeMirrorMode.pde", backup);
  backup=loadStrings("snakeMirrorMovements.pde");
  saveStrings(saveLocation+"backup/snakeMirrorMovements.pde", backup);
  backup=loadStrings("snakeNoWalls.pde");
  saveStrings(saveLocation+"backup/snakeNoWalls.pde", backup);
  backup=loadStrings("snakeNoWallsMirrorMovements.pde");
  saveStrings(saveLocation+"backup/snakeNoWallsMirrorMovements.pde", backup);
  backup=loadStrings("snakeSelection.pde");
  saveStrings(saveLocation+"backup/snakeSelection.pde", backup);
  backup=loadStrings("ttt_pieces.pde");
  saveStrings(saveLocation+"backup/ttt_pieces.pde", backup);
  backup=loadStrings("ttt_tic_tac_toe.pde");
  saveStrings(saveLocation+"backup/ttt_tic_tac_toe.pde", backup);
  backup=loadStrings("update.pde");
  saveStrings(saveLocation+"backup/update.pde", backup);
  backup=loadStrings("yahtzee.pde");
  saveStrings(saveLocation+"backup/yahtzee.pde", backup);
}
