void update() {
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/main_combined_games.pde");
  saveStrings("main_combined_games.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/FB_flappy_bird.pde");
  saveStrings("FB_flappy_bird.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/c4_connect_four.pde");
  saveStrings("c4_connect_four.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/life_game_of_life.pde");
  saveStrings("life_game_of_life.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/m_game_end.pde");
  saveStrings("m_game_end.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/m_movingup.pde");
  saveStrings("m_movingup.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/m_mancala.pde");
  saveStrings("m_mancala.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/m_movingdown.pde");
  saveStrings("m_movingdown.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/pente.pde");
  saveStrings("pente.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/snake.pde");
  saveStrings("snake.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/snakeMirrorMode.pde");
  saveStrings("snakeMirrorMode.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/snakeMirrorMovements.pde");
  saveStrings("snakeMirrorMovements.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/snakeNoWalls.pde");
  saveStrings("snakeNoWalls.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/snakeNoWallsMirrorMovements.pde");
  saveStrings("snakeNoWallsMirrorMovements.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/snakeSelection.pde");
  saveStrings("snakeSelection.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/ttt_pieces.pde");
  saveStrings("ttt_pieces.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/ttt_tic_tac_toe.pde");
  saveStrings("ttt_tic_tac_toe.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/yahtzee.pde");
  saveStrings("yahtzee.pde", update);
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/update.pde");
  saveStrings("update.pde", update);
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/background.png?raw=true");
  update1.save("data/background.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/bird.png?raw=true");
  update1.save("data/bird.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/board.png?raw=true");
  update1.save("data/board.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/bottom.png?raw=true");
  update1.save("data/bottom.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/dice-1.png?raw=true");
  update1.save("data/dice-1.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/dice-2.png?raw=true");
  update1.save("data/dice-2.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/dice-3.png?raw=true");
  update1.save("data/dice-3.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/dice-4.png?raw=true");
  update1.save("data/dice-4.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/dice-5.png?raw=true");
  update1.save("data/dice-5.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/dice-6.png?raw=true");
  update1.save("data/dice-6.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/locked.png?raw=true");
  update1.save("data/locked.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/unlocked.png?raw=true");
  update1.save("data/unlocked.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/pipe%20bottom.png?raw=true");
  update1.save("data/pipe bottom.png");
  update1=loadImage("https://github.com/yzabeast1/combined-games/blob/main/data/pipe%20top.png?raw=true");
  update1.save("data/pipe top.png");
}
void update1() {
  backup();
  update=loadStrings("https://raw.githubusercontent.com/yzabeast1/combined-games/main/update.pde");
  saveStrings("update.pde", update);
}
